### ISSUE TITLE
Failed to build TCP config

### ISSUE THREAD

**Issue by AliSawari** [ImanSeyed/v2ray-uri2json#1]
First of all thank you for this useful tool 👍🏻 

when i run `v2ray run -c config.json` after I  generate the config.json file with the script `vless2json.sh` , I  get this error

> Failed to start: main/commands: failed to load config: [config.json] > infra/conf/v4: Failed to build TCP config. > infra/conf/v4: invalid TCP header config > infra/conf/cfgcommon/loader: unknown config id: 

I think its related to this part of the json file:
```json
 "tcpSettings": {
    "header": {
       "type": ""
     }
   }
```

since the error message is talking about an Invalid TCP Header. after removing the `"header"` property, v2ray command seems to talk about some other invalid option: 

> Failed to start: main/commands: failed to load config: [config.json] > infra/conf/v4: VLESS users: please add/set "encryption":"none" for every user

which is fixed by changing this part of the json file  : 

```json
  "users": [
              {
                "encryption": "",
                "flow": "",
                "id": "d6e4531b-07aa-427b-8b7d",
                "level": 8,
                "security": "auto"
              }
            ]
```

at `"encryption"` and by adding `"none"` instead of an empty " "
only then I could run the v2ray command successfully. I think the `vless2json.sh`  script should also take into consideration the correct property values of a correct v2ray/xray Config file.

**Comment by ImanSeyed** [comment]
Hi there! Thanks for reporting this issue. It’s a bit tough to debug without the URI, so I’ll need your help to fix it properly without causing more issues.

From what I see, the `type` field in the `header` object can be either a `NoneHeaderObject` or an `HttpHeaderObject`, based on this:
https://www.v2ray.com/en/configuration/transport/tcp.html

Looks like ~~I haven’t defined the `$headerType` part anywhere~~, there is no default value for the `$headerType`, so this might also be a problem in `trojan2json.sh`.

Let's test what happens if we set `type` to `none` like this:
```json
"tcpSettings": {
  "header": {
     "type": "none"
   }
 }
```
If it works, we can just get rid of the `$headerType` in `scripts/{vless2json,trojan2json.h}`  and simply replace it with `none`:
```patch
-HEADER_TYPE="$headerType"
+HEADER_TYPE="none"
```
About the second part of your comment, yes, we can definitely do that.
```patch
-ENCRYPTION="$encryption"
+ENCRYPTION="none" 
```
If the changes make it work, feel free to send a PR if you’re up for it. If not, I’ll handle it as soon as I get some free time.

**Comment by AliSawari** [comment]
Certainly! here's a sample URI which I used to generate the config.json file

```
vless://d6e4531b-07aa-427b-8a7d-2d8671ff2317@0.0.0.0:45000?type=tcp&security=none#test-config
```

this URI is being generated by [X-UI](https://github.com/MHSanaei/3x-ui) dashboard for managing v2ray services. and It has some default options ticked. you can see the URL params `&security=none`. the script can read those params and consider them into the generated config.json file.

but nontheless, this configuration indeed worked for me without any issues:

```json
"tcpSettings": {
  "header": {
     "type": "none"
   }
 }
,
"users": [
  {
    "encryption": "none",
    "flow": "",
    "id": "d6e4531b-07aa-427b-8a7d-2d8671ff2317",
    "level": 8,
    "security": "auto"
  }
]
```

So by making these changes to the scripts, It will ignore the value for `$headerType` and `$encryption` and replace all with `none`, correct? 
```diff
-HEADER_TYPE="$headerType"
+HEADER_TYPE="none"

-ENCRYPTION="$encryption"
+ENCRYPTION="none" 
```
what if the values were not  `none` and something like `tls` ? this would generate a wrong config.json which will probably not connect. any solutions for that? I have little experience with bash, can you check the value of a variable in bash for example: 
```bash
if [[ "$encryption" == "none" ]]; then
```
and Yes, I would like to help in a PR for sure :)

**Comment by ImanSeyed** [comment]
> what if the values were not none and something like tls ? this would generate a wrong config.json which will probably not connect.

AFAIK `tls` gets handled in the `security` field, not the `encryption`. 

>I have little experience with bash, can you check the value of a variable in bash for example:
if [[ "$encryption" == "none" ]]; then

Yes, but in this case, it's unnecessary because Vless doesn't support encryption. We can set it to `none` without any condition. A way to solve it is this:
```bash
ENCRYPTION=${encryption:-none}
HEADER_TYPE=${headerType:-none}
```
